services:
  mockserver-target:
    image: mockserver/mockserver:latest
    ports:
      - "4567:4567"
    environment:
      MOCKSERVER_LOG_LEVEL: INFO
      MOCKSERVER_SERVER_PORT: 4567
  mockserver:
    image: mockserver/mockserver:latest
    ports:
      - "1234:1234"
    environment:
      MOCKSERVER_LOG_LEVEL: INFO
      MOCKSERVER_SERVER_PORT: 1234
      PROXY_REMOTE_HOST: mockserver-target
      PROXY_REMOTE_PORT: 4567
