steps:
  - label: ":s3: restore bundler cache"
    command: ".buildkite/scripts/cache-restore.sh bundler"
    timeout_in_minutes: 10
    soft_fail: true

  - wait

  - label: ":jekyll: validate Jekyll site"
    command: ".buildkite/scripts/steps/website-build.sh"
    timeout_in_minutes: 10

  - wait: ~
    continue_on_failure: true

  - label: ":s3: save bundler cache"
    command: ".buildkite/scripts/cache-save.sh bundler"
    timeout_in_minutes: 10
    soft_fail: true
