// <auto-generated>
// Composer C# codegen equivalence proof.
//
// This test constructs the SAME typed `Expectation` graphs the dashboard composer's
// C# emitter (mockserver-ui/src/lib/codegen/csharp.ts -> standardToCsharp) produces,
// serialises them with the client's canonical options, and asserts the resulting JSON
// is equivalent to the wire payload the composer computes (buildExpectationJson).
//
// The C# construction snippets below are the emitter's verbatim output; the reference
// JSON strings are the emitter's own `buildExpectationJson` output. Both were captured
// together so this file is a faithful, self-contained proof that the emitted typed code
// (a) compiles and (b) round-trips to the intended wire shape. It is a frozen snapshot:
// if the emitter changes, re-capture the constructions and reference JSON from
// standardToCsharp / buildExpectationJson over the same cases.
//
// Two families of tests:
//   * Strict_*      — full JsonNode.DeepEquals, no normalisation (the strong proof).
//   * Divergence_*  — equivalence under two documented, server-accepted divergences the
//                     .NET client models differently: a JSON body's `json` emitted as a
//                     string vs. an inline object, and an override-forwarded-request's
//                     override under `httpRequest` (server @JsonAlias) vs. `requestOverride`.
// </auto-generated>
#nullable enable
using System.Text.Json;
using System.Text.Json.Nodes;
using FluentAssertions;
using MockServer.Client.Models;
using MockServer.Client.Llm;
using Xunit;

namespace MockServer.Client.Tests;

public class ComposerCodegenEquivalenceTests
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
    };

    private static void AssertStrict(Expectation expectation, string referenceJson)
    {
        var actual = JsonNode.Parse(JsonSerializer.Serialize(expectation, JsonOptions));
        var expected = JsonNode.Parse(referenceJson);
        JsonNode.DeepEquals(actual, expected)
            .Should().BeTrue($"typed construction must serialise byte-equivalently; got: {actual}");
    }

    private static void AssertEquivalentUnderKnownDivergences(Expectation expectation, string referenceJson)
    {
        var actual = Normalize(JsonNode.Parse(JsonSerializer.Serialize(expectation, JsonOptions)));
        var expected = Normalize(JsonNode.Parse(referenceJson));
        JsonNode.DeepEquals(actual, expected)
            .Should().BeTrue($"typed construction must be equivalent under documented divergences; got: {actual}");
    }

    // Canonicalise the two documented, server-accepted divergences so both sides compare
    // equal iff they differ ONLY by those representations (any other diff still fails).
    private static JsonNode? Normalize(JsonNode? node)
    {
        switch (node)
        {
            case JsonObject obj:
            {
                var result = new JsonObject();
                foreach (var kv in obj)
                {
                    // (2) override-forwarded-request: requestOverride == httpRequest.
                    var key = kv.Key == "requestOverride" ? "httpRequest" : kv.Key;
                    var value = kv.Value;
                    // (1) JSON body: a "json" string that parses as JSON == the inline object.
                    if (key == "json" && value is JsonValue v && v.TryGetValue<string>(out var s))
                    {
                        JsonNode? parsed = null;
                        try { parsed = JsonNode.Parse(s); } catch { /* leave as string */ }
                        if (parsed is not null) { result[key] = Normalize(parsed); continue; }
                    }
                    result[key] = Normalize(value);
                }
                return result;
            }
            case JsonArray arr:
            {
                var result = new JsonArray();
                foreach (var el in arr) result.Add(Normalize(el));
                return result;
            }
            default:
                return node?.DeepClone();
        }
    }

    // ---- Negative control: a deliberately-wrong construction must NOT pass. ----
    [Fact]
    public void NegativeControl_WrongStatusCode_Fails()
    {
        var wrong = new Expectation
        {
            HttpRequest = new HttpRequest { Method = "GET", Path = "/api" },
            HttpResponse = new HttpResponse { StatusCode = 418 },
        };
        var actual = JsonNode.Parse(JsonSerializer.Serialize(wrong, JsonOptions));
        var expected = JsonNode.Parse(@"{""httpRequest"":{""path"":""/api"",""method"":""GET""},""httpResponse"":{""statusCode"":200}}");
        JsonNode.DeepEquals(actual, expected).Should().BeFalse();
    }

    [Fact]
    public void Strict_jwt_regex_strict() => AssertStrict(
        new Expectation
        {
            Priority = 5,
            HttpRequest = new HttpRequest
            {
                Method = "PUT",
                Path = "/account",
                Headers = new Dictionary<string, List<string>>
                {
                    ["Accept"] = new() { "application/json" },
                },
                QueryStringParameters = new Dictionary<string, List<string>>
                {
                    ["v"] = new() { "2" },
                },
                Cookies = new Dictionary<string, string>
                {
                    ["sid"] = "1",
                },
                PathParameters = new Dictionary<string, List<JsonElement>>
                {
                    ["id"] = new() { JsonSerializer.SerializeToElement("42") },
                },
                Body = Body.OfRegex("a.*z"),
                Jwt = new Jwt
                {
                    Header = "x-auth",
                    Scheme = "Token",
                    Claims = new Dictionary<string, string>
                    {
                        ["sub"] = "user1",
                        ["role"] = "admin",
                    },
                    Issuer = "iss",
                    Audience = "aud",
                    Algorithm = "RS256",
                },
                Secure = true,
            },
            HttpResponse = new HttpResponse
            {
                StatusCode = 200,
                Headers = new Dictionary<string, List<string>>
                {
                    ["content-type"] = new() { "text/plain" },
                },
                Body = "ok",
            },
            Times = Times.Exactly(2),
            TimeToLive = TimeToLive.ExactlyTtl(TimeUnit.SECONDS, 60),
        },
        @"{""httpRequest"":{""path"":""/account"",""method"":""PUT"",""headers"":{""Accept"":[""application/json""]},""queryStringParameters"":{""v"":[""2""]},""cookies"":{""sid"":""1""},""pathParameters"":{""id"":[""42""]},""body"":{""type"":""REGEX"",""regex"":""a.*z""},""jwt"":{""header"":""x-auth"",""scheme"":""Token"",""claims"":{""sub"":""user1"",""role"":""admin""},""issuer"":""iss"",""audience"":""aud"",""algorithm"":""RS256""},""secure"":true},""httpResponse"":{""statusCode"":200,""body"":""ok"",""headers"":{""content-type"":[""text/plain""]}},""priority"":5,""times"":{""remainingTimes"":2,""unlimited"":false},""timeToLive"":{""timeUnit"":""SECONDS"",""timeToLive"":60,""unlimited"":false}}");

    [Fact]
    public void Strict_static_file_body_full() => AssertStrict(
        new Expectation
        {
            HttpRequest = new HttpRequest
            {
                Method = "POST",
                Path = "/orders",
            },
            HttpResponse = new HttpResponse
            {
                StatusCode = 201,
                ReasonPhrase = "Created",
                Headers = new Dictionary<string, List<string>>
                {
                    ["X-Trace"] = new() { "abc" },
                    ["X-Env"] = new() { "prod" },
                },
                Cookies = new Dictionary<string, string>
                {
                    ["session"] = "xyz",
                    ["theme"] = "dark",
                },
                Body = new FileBody
                {
                    FilePath = "responses/order.json",
                    ContentType = "application/json",
                    TemplateType = FileTemplateType.MUSTACHE,
                },
                Delay = new Delay { TimeUnit = TimeUnit.MILLISECONDS, Value = 250 },
                ConnectionOptions = new ConnectionOptions { KeepAliveOverride = true, CloseSocket = false, SuppressContentLengthHeader = true },
            },
        },
        @"{""httpRequest"":{""path"":""/orders"",""method"":""POST""},""httpResponse"":{""statusCode"":201,""body"":{""type"":""FILE"",""filePath"":""responses/order.json"",""templateType"":""MUSTACHE"",""contentType"":""application/json""},""headers"":{""X-Trace"":[""abc""],""X-Env"":[""prod""]},""connectionOptions"":{""keepAliveOverride"":true,""closeSocket"":false,""suppressContentLengthHeader"":true},""reasonPhrase"":""Created"",""cookies"":{""session"":""xyz"",""theme"":""dark""},""delay"":{""timeUnit"":""MILLISECONDS"",""value"":250}}}");

    [Fact]
    public void Strict_simple_static() => AssertStrict(
        new Expectation
        {
            HttpRequest = new HttpRequest
            {
                Method = "GET",
                Path = "/api",
            },
            HttpResponse = new HttpResponse
            {
                StatusCode = 200,
                Headers = new Dictionary<string, List<string>>
                {
                    ["content-type"] = new() { "text/plain" },
                },
                Body = "hello",
            },
        },
        @"{""httpRequest"":{""path"":""/api"",""method"":""GET""},""httpResponse"":{""statusCode"":200,""body"":""hello"",""headers"":{""content-type"":[""text/plain""]}}}");

    [Fact]
    public void Strict_forward() => AssertStrict(
        new Expectation
        {
            HttpRequest = new HttpRequest
            {
                Method = "GET",
                Path = "/api",
            },
            HttpForward = HttpForward.Forward()
                .WithScheme("HTTPS")
                .WithHost("upstream.example.com")
                .WithPort(8443)
                .Build(),
        },
        @"{""httpRequest"":{""path"":""/api"",""method"":""GET""},""httpForward"":{""scheme"":""HTTPS"",""host"":""upstream.example.com"",""port"":8443}}");

    [Fact]
    public void Strict_error() => AssertStrict(
        new Expectation
        {
            HttpRequest = new HttpRequest
            {
                Method = "GET",
                Path = "/api",
            },
            HttpError = HttpError.Error()
                .WithDropConnection(true)
                .WithResponseBytes("AQIDBA==")
                .WithDelay(TimeUnit.SECONDS, 5)
                .Build(),
        },
        @"{""httpRequest"":{""path"":""/api"",""method"":""GET""},""httpError"":{""dropConnection"":true,""responseBytes"":""AQIDBA=="",""delay"":{""timeUnit"":""SECONDS"",""value"":5}}}");

    [Fact]
    public void Strict_forward_fallback() => AssertStrict(
        new Expectation
        {
            HttpRequest = new HttpRequest
            {
                Method = "GET",
                Path = "/api",
            },
            HttpForwardWithFallback = new HttpForwardWithFallback
            {
                HttpForward = HttpForward.Forward()
                    .WithScheme("HTTP")
                    .WithHost("primary.example.com")
                    .WithPort(80)
                    .Build(),
                FallbackResponse = new HttpResponse
                {
                    StatusCode = 503,
                    Body = "unavailable",
                },
                FallbackOnStatusCodes = new List<int> { 500, 502, 503 },
                FallbackOnTimeout = true,
            },
        },
        @"{""httpRequest"":{""path"":""/api"",""method"":""GET""},""httpForwardWithFallback"":{""httpForward"":{""scheme"":""HTTP"",""host"":""primary.example.com"",""port"":80},""fallbackResponse"":{""statusCode"":503,""body"":""unavailable""},""fallbackOnStatusCodes"":[500,502,503],""fallbackOnTimeout"":true}}");

    [Fact]
    public void Strict_websocket() => AssertStrict(
        new Expectation
        {
            HttpRequest = new HttpRequest
            {
                Method = "GET",
                Path = "/api",
            },
            HttpWebSocketResponse = new HttpWebSocketResponse
            {
                Subprotocol = "chat",
                Messages = new List<WebSocketMessage>
                {
                    WebSocketMessage.OfText("hello"),
                    WebSocketMessage.OfText("world"),
                },
                Matchers = new List<WebSocketFrameMatcher>
                {
                    new WebSocketFrameMatcher
                    {
                        FrameType = "TEXT",
                        TextMatcher = "ping",
                        Responses = new List<WebSocketMessage>
                        {
                            WebSocketMessage.OfText("pong"),
                            WebSocketMessage.OfText("ack"),
                        },
                    },
                },
            },
        },
        @"{""httpRequest"":{""path"":""/api"",""method"":""GET""},""httpWebSocketResponse"":{""subprotocol"":""chat"",""messages"":[{""text"":""hello""},{""text"":""world""}],""matchers"":[{""frameType"":""TEXT"",""textMatcher"":""ping"",""responses"":[{""text"":""pong""},{""text"":""ack""}]}]}}");

    [Fact]
    public void Strict_sse() => AssertStrict(
        new Expectation
        {
            HttpRequest = new HttpRequest
            {
                Method = "GET",
                Path = "/api",
            },
            HttpSseResponse = new HttpSseResponse
            {
                StatusCode = 200,
                Headers = new Dictionary<string, List<string>>
                {
                    ["Cache-Control"] = new() { "no-cache" },
                },
                Events = new List<SseEvent>
                {
                    new SseEvent
                    {
                        Event = "msg",
                        Data = "tick",
                        Id = "1",
                        Retry = 1000,
                    },
                },
            },
        },
        @"{""httpRequest"":{""path"":""/api"",""method"":""GET""},""httpSseResponse"":{""statusCode"":200,""headers"":{""Cache-Control"":[""no-cache""]},""events"":[{""event"":""msg"",""data"":""tick"",""id"":""1"",""retry"":1000}]}}");

    [Fact]
    public void Strict_dns() => AssertStrict(
        new Expectation
        {
            HttpRequest = new HttpRequest
            {
                DnsName = "example.com",
                DnsType = "A",
                DnsClass = "IN",
            },
            DnsResponse = new DnsResponse
            {
                ResponseCode = "NOERROR",
                AnswerRecords = new List<DnsRecord>
                {
                    new DnsRecord
                    {
                        Name = "example.com",
                        Type = "A",
                        Ttl = 300,
                        Value = "1.2.3.4",
                    },
                },
            },
        },
        @"{""httpRequest"":{""dnsName"":""example.com"",""dnsType"":""A"",""dnsClass"":""IN""},""dnsResponse"":{""responseCode"":""NOERROR"",""answerRecords"":[{""name"":""example.com"",""type"":""A"",""ttl"":300,""value"":""1.2.3.4""}]}}");

    [Fact]
    public void Strict_grpc_stream() => AssertStrict(
        new Expectation
        {
            HttpRequest = new HttpRequest
            {
                Method = "GET",
                Path = "/api",
            },
            GrpcStreamResponse = new GrpcStreamResponse
            {
                StatusName = "OK",
                Headers = new Dictionary<string, List<string>>
                {
                    ["grpc-encoding"] = new() { "identity" },
                },
                Messages = new List<GrpcStreamMessage>
                {
                    GrpcStreamMessage.OfJson("{\"a\":1}"),
                    GrpcStreamMessage.OfJson("{\"b\":2}"),
                },
            },
        },
        @"{""httpRequest"":{""path"":""/api"",""method"":""GET""},""grpcStreamResponse"":{""statusName"":""OK"",""headers"":{""grpc-encoding"":[""identity""]},""messages"":[{""json"":""{\""a\"":1}""},{""json"":""{\""b\"":2}""}]}}");

    [Fact]
    public void Strict_binary_response() => AssertStrict(
        new Expectation
        {
            HttpRequest = new HttpRequest
            {
                Method = "GET",
                Path = "/api",
            },
            BinaryResponse = new BinaryResponse
            {
                BinaryData = "SGVsbG8=",
            },
        },
        @"{""httpRequest"":{""path"":""/api"",""method"":""GET""},""binaryResponse"":{""binaryData"":""SGVsbG8=""}}");

    [Fact]
    public void Strict_callback() => AssertStrict(
        new Expectation
        {
            HttpRequest = new HttpRequest
            {
                Method = "GET",
                Path = "/api",
            },
            HttpResponseClassCallback = new HttpClassCallback
            {
                CallbackClass = "com.example.MyCallback",
            },
        },
        @"{""httpRequest"":{""path"":""/api"",""method"":""GET""},""httpResponseClassCallback"":{""callbackClass"":""com.example.MyCallback""}}");

    [Fact]
    public void Strict_template_velocity() => AssertStrict(
        new Expectation
        {
            HttpRequest = new HttpRequest
            {
                Method = "GET",
                Path = "/api",
            },
            HttpResponseTemplate = HttpTemplate.OfType(TemplateType.VELOCITY)
                .WithTemplate("$!request.body")
                .Build(),
        },
        @"{""httpRequest"":{""path"":""/api"",""method"":""GET""},""httpResponseTemplate"":{""templateType"":""VELOCITY"",""template"":""$!request.body""}}");

    [Fact]
    public void Strict_capture_scenario_sideEffects() => AssertStrict(
        new Expectation
        {
            HttpRequest = new HttpRequest
            {
                Method = "POST",
                Path = "/checkout",
            },
            HttpResponse = new HttpResponse
            {
                StatusCode = 200,
                Headers = new Dictionary<string, List<string>>
                {
                    ["content-type"] = new() { "text/plain" },
                },
                Body = "ok",
            },
            AfterActions = new List<AfterAction>
            {
                new AfterAction
                {
                    HttpRequest = new HttpRequest
                    {
                        Method = "POST",
                        Path = "/audit",
                        Headers = new Dictionary<string, List<string>>
                        {
                            ["Host"] = new() { "audit.example.com" },
                        },
                        Body = "{\"logged\":true}",
                    },
                },
            },
            Capture = new List<CaptureRule>
            {
                CaptureRule.Of("jsonPath", "$.token", "authToken"),
            },
            ScenarioName = "login",
            ScenarioState = "START",
            NewScenarioState = "DONE",
        },
        @"{""httpRequest"":{""path"":""/checkout"",""method"":""POST""},""httpResponse"":{""statusCode"":200,""body"":""ok"",""headers"":{""content-type"":[""text/plain""]}},""afterActions"":[{""httpRequest"":{""path"":""/audit"",""method"":""POST"",""headers"":{""Host"":[""audit.example.com""]},""body"":""{\""logged\"":true}""}}],""capture"":[{""source"":""jsonPath"",""expression"":""$.token"",""into"":""authToken""}],""scenarioName"":""login"",""scenarioState"":""START"",""newScenarioState"":""DONE""}");

    [Fact]
    public void Strict_steps_pipeline() => AssertStrict(
        new Expectation
        {
            HttpRequest = new HttpRequest
            {
                Method = "GET",
                Path = "/pipeline",
            },
            Steps = new List<ExpectationStep>
            {
                new ExpectationStep
                {
                    HttpResponse = JsonSerializer.Deserialize<HttpResponse>(@"{""statusCode"":200,""body"":""step""}"),
                    Responder = true,
                },
                new ExpectationStep
                {
                    HttpRequest = JsonSerializer.Deserialize<HttpRequest>(@"{""path"":""/hook""}"),
                    Delay = new Delay { TimeUnit = TimeUnit.MILLISECONDS, Value = 100 },
                    Timeout = new Delay { TimeUnit = TimeUnit.SECONDS, Value = 2 },
                    FailurePolicy = ActionFailurePolicy.FAIL_FAST,
                },
            },
        },
        @"{""httpRequest"":{""path"":""/pipeline"",""method"":""GET""},""steps"":[{""httpResponse"":{""statusCode"":200,""body"":""step""},""responder"":true},{""httpRequest"":{""path"":""/hook""},""delay"":{""timeUnit"":""MILLISECONDS"",""value"":100},""timeout"":{""timeUnit"":""SECONDS"",""value"":2},""failurePolicy"":""FAIL_FAST""}]}");

    [Fact]
    public void Strict_chaos_full() => AssertStrict(
        new Expectation
        {
            Priority = 3,
            HttpRequest = new HttpRequest
            {
                Method = "POST",
                Path = "/chaos",
            },
            HttpResponse = new HttpResponse
            {
                StatusCode = 200,
                Headers = new Dictionary<string, List<string>>
                {
                    ["content-type"] = new() { "text/plain" },
                },
                Body = "ok",
            },
            Chaos = new HttpChaosProfile
            {
                ErrorStatus = 503,
                ErrorProbability = 0.5,
                RetryAfter = "2",
                Seed = 42,
                SucceedFirst = 1,
                FailRequestCount = 2,
                Latency = new Delay { TimeUnit = TimeUnit.MILLISECONDS, Value = 100 },
            },
            Times = Times.Exactly(4),
            TimeToLive = TimeToLive.ExactlyTtl(TimeUnit.SECONDS, 30),
        },
        @"{""httpRequest"":{""path"":""/chaos"",""method"":""POST""},""httpResponse"":{""statusCode"":200,""body"":""ok"",""headers"":{""content-type"":[""text/plain""]}},""chaos"":{""errorStatus"":503,""errorProbability"":0.5,""retryAfter"":""2"",""latency"":{""timeUnit"":""MILLISECONDS"",""value"":100},""seed"":42,""succeedFirst"":1,""failRequestCount"":2},""priority"":3,""times"":{""remainingTimes"":4,""unlimited"":false},""timeToLive"":{""timeUnit"":""SECONDS"",""timeToLive"":30,""unlimited"":false}}");

    [Fact]
    public void Divergence_json_body_jwt_secure() => AssertEquivalentUnderKnownDivergences(
        new Expectation
        {
            Priority = 5,
            HttpRequest = new HttpRequest
            {
                Method = "PUT",
                Path = "/account",
                Headers = new Dictionary<string, List<string>>
                {
                    ["Accept"] = new() { "application/json" },
                },
                QueryStringParameters = new Dictionary<string, List<string>>
                {
                    ["v"] = new() { "2" },
                },
                Cookies = new Dictionary<string, string>
                {
                    ["sid"] = "1",
                },
                PathParameters = new Dictionary<string, List<JsonElement>>
                {
                    ["id"] = new() { JsonSerializer.SerializeToElement("42") },
                },
                Body = Body.OfJson("{\"ok\":true,\"n\":3}", "STRICT"),
                Jwt = new Jwt
                {
                    Header = "x-auth",
                    Scheme = "Token",
                    Claims = new Dictionary<string, string>
                    {
                        ["sub"] = "user1",
                        ["role"] = "admin",
                    },
                    Issuer = "iss",
                    Audience = "aud",
                    Algorithm = "RS256",
                },
                Secure = true,
            },
            HttpResponse = new HttpResponse
            {
                StatusCode = 200,
            },
            Times = Times.Exactly(2),
            TimeToLive = TimeToLive.ExactlyTtl(TimeUnit.SECONDS, 60),
        },
        @"{""httpRequest"":{""path"":""/account"",""method"":""PUT"",""headers"":{""Accept"":[""application/json""]},""queryStringParameters"":{""v"":[""2""]},""cookies"":{""sid"":""1""},""pathParameters"":{""id"":[""42""]},""body"":{""type"":""JSON"",""json"":{""ok"":true,""n"":3},""matchType"":""STRICT""},""jwt"":{""header"":""x-auth"",""scheme"":""Token"",""claims"":{""sub"":""user1"",""role"":""admin""},""issuer"":""iss"",""audience"":""aud"",""algorithm"":""RS256""},""secure"":true},""httpResponse"":{""statusCode"":200},""priority"":5,""times"":{""remainingTimes"":2,""unlimited"":false},""timeToLive"":{""timeUnit"":""SECONDS"",""timeToLive"":60,""unlimited"":false}}");

    [Fact]
    public void Divergence_allOf_body() => AssertEquivalentUnderKnownDivergences(
        new Expectation
        {
            HttpRequest = new HttpRequest
            {
                Method = "POST",
                Path = "/api",
                Body = Body.OfAllOf(
                    Body.OfJson("{\"k\":1}"),
                    Body.OfXPath("/a/b"),
                    Body.OfRegex(".*foo.*")),
            },
            HttpResponse = new HttpResponse
            {
                StatusCode = 200,
                Headers = new Dictionary<string, List<string>>
                {
                    ["content-type"] = new() { "text/plain" },
                },
                Body = "ok",
            },
        },
        @"{""httpRequest"":{""path"":""/api"",""method"":""POST"",""body"":{""type"":""ALL_OF"",""bodyAllOf"":[{""type"":""JSON"",""json"":{""k"":1}},{""type"":""XPATH"",""xpath"":""/a/b""},{""type"":""REGEX"",""regex"":"".*foo.*""}]}},""httpResponse"":{""statusCode"":200,""body"":""ok"",""headers"":{""content-type"":[""text/plain""]}}}");

    [Fact]
    public void Divergence_forward_override() => AssertEquivalentUnderKnownDivergences(
        new Expectation
        {
            HttpRequest = new HttpRequest
            {
                Method = "GET",
                Path = "/api",
            },
            HttpOverrideForwardedRequest = new HttpOverrideForwardedRequest
            {
                HttpRequest = new HttpRequest
                {
                    Method = "PATCH",
                    Path = "/v2/api",
                    Headers = new Dictionary<string, List<string>>
                    {
                        ["X-Fwd"] = new() { "yes" },
                        ["Host"] = new() { "rewrite.example.com" },
                    },
                    QueryStringParameters = new Dictionary<string, List<string>>
                    {
                        ["debug"] = new() { "1" },
                    },
                    Body = "{\"patched\":true}",
                    Secure = true,
                },
            },
        },
        @"{""httpRequest"":{""path"":""/api"",""method"":""GET""},""httpOverrideForwardedRequest"":{""requestOverride"":{""method"":""PATCH"",""secure"":true,""path"":""/v2/api"",""headers"":{""X-Fwd"":[""yes""],""Host"":[""rewrite.example.com""]},""queryStringParameters"":{""debug"":[""1""]},""body"":""{\""patched\"":true}""}}}");

    // ---- Edit-preserved actions/siblings the standard composer form cannot model ----
    // These arrive via an edit overlay (editActionModeled === false / sibling
    // passthrough) and MUST be emitted as TYPED object initializers — previously the
    // C# emitter degraded them to JsonSerializer.Deserialize<T>(@"json") fragments.

    [Fact]
    public void Strict_preserved_llm_completion() => AssertStrict(
        new Expectation
        {
            HttpRequest = new HttpRequest
            {
                Method = "POST",
                Path = "/v1/messages",
            },
            HttpLlmResponse = new HttpLlmResponse
            {
                Provider = "ANTHROPIC",
                Model = "claude-sonnet-4-20250514",
                Completion = new Completion
                {
                    Text = "Hello, world!",
                    ToolCalls = new List<ToolUse>
                    {
                        new ToolUse
                        {
                            Id = "call_1",
                            Name = "get_weather",
                            Arguments = "{\"city\":\"SF\"}",
                        },
                    },
                    StopReason = "end_turn",
                    Usage = new Usage
                    {
                        InputTokens = 10,
                        OutputTokens = 25,
                        CachedInputTokens = 2,
                        CacheCreationTokens = 3,
                        ReasoningTokens = 4,
                    },
                    Streaming = true,
                    StreamingPhysics = new StreamingPhysics
                    {
                        TokensPerSecond = 50,
                        Jitter = 0.2,
                        Seed = 7,
                        SubwordStreaming = true,
                    },
                    OutputSchema = "{\"type\":\"object\"}",
                    EnforceOutputSchema = true,
                    ToolChoice = "auto",
                    ReasoningText = "thinking",
                    ReasoningSignature = "sig",
                    Model = "claude-sonnet-4-20250514",
                },
                ConversationPredicates = new ConversationPredicates
                {
                    TurnIndex = 1,
                    LatestMessageContains = "weather",
                    LatestMessageMatches = ".*weather.*",
                    LatestMessageRole = "USER",
                    ContainsToolResultFor = "get_weather",
                    SemanticMatchAgainst = "weather query",
                    Normalization = new NormalizationOptions
                    {
                        CollapseWhitespace = true,
                        Lowercase = true,
                        SortJsonKeys = true,
                        DropBuiltInVolatileFields = true,
                        DropVolatileFields = new() { "id", "created" },
                    },
                },
                Delay = new Delay { TimeUnit = TimeUnit.MILLISECONDS, Value = 15 },
                Primary = true,
            },
        },
        @"{""httpRequest"":{""method"":""POST"",""path"":""/v1/messages""},""httpLlmResponse"":{""provider"":""ANTHROPIC"",""model"":""claude-sonnet-4-20250514"",""delay"":{""timeUnit"":""MILLISECONDS"",""value"":15},""completion"":{""text"":""Hello, world!"",""toolCalls"":[{""id"":""call_1"",""name"":""get_weather"",""arguments"":""{\""city\"":\""SF\""}""}],""stopReason"":""end_turn"",""usage"":{""inputTokens"":10,""outputTokens"":25,""cachedInputTokens"":2,""cacheCreationTokens"":3,""reasoningTokens"":4},""streaming"":true,""outputSchema"":""{\""type\"":\""object\""}"",""enforceOutputSchema"":true,""toolChoice"":""auto"",""reasoningText"":""thinking"",""reasoningSignature"":""sig"",""model"":""claude-sonnet-4-20250514"",""streamingPhysics"":{""tokensPerSecond"":50,""jitter"":0.2,""seed"":7,""subwordStreaming"":true}},""conversationPredicates"":{""turnIndex"":1,""latestMessageContains"":""weather"",""latestMessageMatches"":"".*weather.*"",""latestMessageRole"":""USER"",""containsToolResultFor"":""get_weather"",""semanticMatchAgainst"":""weather query"",""normalization"":{""collapseWhitespace"":true,""lowercase"":true,""sortJsonKeys"":true,""dropBuiltInVolatileFields"":true,""dropVolatileFields"":[""id"",""created""]}},""primary"":true}}");

    [Fact]
    public void Strict_preserved_response_sequence() => AssertStrict(
        new Expectation
        {
            HttpRequest = new HttpRequest
            {
                Method = "GET",
                Path = "/seq",
            },
            HttpResponses = new List<HttpResponse>
            {
                new HttpResponse
                {
                    StatusCode = 200,
                    Body = "first",
                },
                new HttpResponse
                {
                    StatusCode = 201,
                    Headers = new Dictionary<string, List<string>>
                    {
                        ["content-type"] = new() { "text/plain" },
                    },
                    Body = "second",
                },
            },
            ResponseMode = ResponseMode.WEIGHTED,
            ResponseWeights = new List<int> { 3, 1 },
            SwitchAfter = 5,
        },
        @"{""httpRequest"":{""method"":""GET"",""path"":""/seq""},""httpResponses"":[{""statusCode"":200,""body"":""first""},{""statusCode"":201,""body"":""second"",""headers"":{""content-type"":[""text/plain""]}}],""responseMode"":""WEIGHTED"",""responseWeights"":[3,1],""switchAfter"":5}");

    [Fact]
    public void Strict_preserved_rate_limit() => AssertStrict(
        new Expectation
        {
            Percentage = 50,
            HttpRequest = new HttpRequest
            {
                Method = "GET",
                Path = "/rl",
            },
            HttpResponse = new HttpResponse
            {
                StatusCode = 200,
                Body = "ok",
            },
            RateLimit = new RateLimit
            {
                Name = "api",
                Algorithm = "token_bucket",
                Limit = 100,
                WindowMillis = 60000,
                Burst = 20,
                RefillPerSecond = 5m,
                ErrorStatus = 429,
                RetryAfter = "1",
            },
        },
        @"{""httpRequest"":{""method"":""GET"",""path"":""/rl""},""rateLimit"":{""name"":""api"",""algorithm"":""token_bucket"",""limit"":100,""windowMillis"":60000,""burst"":20,""refillPerSecond"":5,""errorStatus"":429,""retryAfter"":""1""},""percentage"":50,""httpResponse"":{""statusCode"":200,""body"":""ok""}}");

    [Fact]
    public void Strict_preserved_cross_protocol() => AssertStrict(
        new Expectation
        {
            Percentage = 25,
            Namespace = "team-a",
            HttpRequest = new HttpRequest
            {
                Method = "GET",
                Path = "/xp",
            },
            HttpResponse = new HttpResponse
            {
                StatusCode = 200,
                Body = "ok",
            },
            CrossProtocolScenarios = new List<CrossProtocolScenario>
            {
                new CrossProtocolScenario
                {
                    Trigger = CrossProtocolTrigger.DNS_QUERY,
                    MatchPattern = "*.example.com",
                    ScenarioName = "dns-scn",
                    TargetState = "RESOLVED",
                },
            },
            Timestamp = "2026-01-01T00:00:00Z",
        },
        @"{""httpRequest"":{""method"":""GET"",""path"":""/xp""},""crossProtocolScenarios"":[{""trigger"":""DNS_QUERY"",""matchPattern"":""*.example.com"",""scenarioName"":""dns-scn"",""targetState"":""RESOLVED""}],""namespace"":""team-a"",""timestamp"":""2026-01-01T00:00:00Z"",""percentage"":25,""httpResponse"":{""statusCode"":200,""body"":""ok""}}");
}
