package org.mockserver.llm.codec;

import org.junit.Test;

import java.util.Locale;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.*;

/**
 * Contract for the deterministic embedding vectors produced by
 * {@link EmbeddingVectors#generateDeterministicVector(String, int, long)}.
 * <p>
 * The vector is generated by n-gram feature hashing, so it is pinned to its
 * <em>behavioural</em> contract — determinism, L2 normalisation, dimension /
 * seed independence, and (crucially) that semantically related texts rank
 * above unrelated ones by cosine similarity — rather than to exact float
 * values.
 */
public class EmbeddingDeterminismTest {

    private static double cosine(double[] a, double[] b) {
        double dot = 0, na = 0, nb = 0;
        for (int i = 0; i < a.length; i++) {
            dot += a[i] * b[i];
            na += a[i] * a[i];
            nb += b[i] * b[i];
        }
        double denom = Math.sqrt(na) * Math.sqrt(nb);
        return denom == 0 ? 0 : dot / denom;
    }

    private static double[] normalized(String input, int dimensions, long seed) {
        double[] vector = EmbeddingVectors.generateDeterministicVector(input, dimensions, seed);
        EmbeddingVectors.normalizeL2(vector);
        return vector;
    }

    @Test
    public void shouldProduceIdenticalVectorForSameInputAndSeed() {
        // given
        String input = "test input text";
        int dimensions = 128;
        long seed = 42;

        // when
        double[] vector1 = EmbeddingVectors.generateDeterministicVector(input, dimensions, seed);
        double[] vector2 = EmbeddingVectors.generateDeterministicVector(input, dimensions, seed);

        // then
        assertThat(vector1.length, is(dimensions));
        assertThat(vector2.length, is(dimensions));
        for (int i = 0; i < dimensions; i++) {
            assertThat("element " + i + " should be identical",
                vector1[i], is(vector2[i]));
        }
    }

    @Test
    public void shouldProduceL2NormalizedVector() {
        // given
        String input = "test input text";
        int dimensions = 256;
        long seed = 42;

        // when
        double[] vector = EmbeddingVectors.generateDeterministicVector(input, dimensions, seed);
        EmbeddingVectors.normalizeL2(vector);

        // then — L2 norm should be approximately 1.0
        double sumOfSquares = 0;
        for (double v : vector) {
            sumOfSquares += v * v;
        }
        double norm = Math.sqrt(sumOfSquares);
        assertThat(norm, is(closeTo(1.0, 1e-10)));
    }

    @Test
    public void shouldProduceIndependentVectorsForDifferentDimensions() {
        // given
        String input = "test input text";
        long seed = 42;

        // when
        double[] vector128 = EmbeddingVectors.generateDeterministicVector(input, 128, seed);
        double[] vector256 = EmbeddingVectors.generateDeterministicVector(input, 256, seed);

        // then — vectors have different lengths
        assertThat(vector128.length, is(128));
        assertThat(vector256.length, is(256));

        // The 128-dim vector must NOT be a prefix of the 256-dim vector —
        // different dimensions hash features into different bucket counts so
        // the two vectors are unrelated. At least one element in the shared
        // prefix range must differ.
        boolean atLeastOneElementDiffers = false;
        for (int i = 0; i < 128; i++) {
            if (vector128[i] != vector256[i]) {
                atLeastOneElementDiffers = true;
                break;
            }
        }
        assertThat("128-dim vector must be independent of the 256-dim prefix",
            atLeastOneElementDiffers, is(true));
    }

    @Test
    public void shouldProduceDifferentVectorsForDifferentInputs() {
        // given
        int dimensions = 128;
        long seed = 42;

        // when
        double[] vector1 = EmbeddingVectors.generateDeterministicVector("input A", dimensions, seed);
        double[] vector2 = EmbeddingVectors.generateDeterministicVector("input B", dimensions, seed);

        // then — at least some elements should differ
        boolean anyDifferent = false;
        for (int i = 0; i < dimensions; i++) {
            if (vector1[i] != vector2[i]) {
                anyDifferent = true;
                break;
            }
        }
        assertThat("different inputs should produce different vectors", anyDifferent, is(true));
    }

    @Test
    public void shouldProduceDifferentVectorsForDifferentSeeds() {
        // given
        String input = "same input";
        int dimensions = 128;

        // when
        double[] vector1 = EmbeddingVectors.generateDeterministicVector(input, dimensions, 1);
        double[] vector2 = EmbeddingVectors.generateDeterministicVector(input, dimensions, 2);

        // then — at least some elements should differ
        boolean anyDifferent = false;
        for (int i = 0; i < dimensions; i++) {
            if (vector1[i] != vector2[i]) {
                anyDifferent = true;
                break;
            }
        }
        assertThat("different seeds should produce different vectors", anyDifferent, is(true));
    }

    @Test
    public void shouldProduceNormalizedValuesInUnitRange() {
        // given — every component of a unit vector is within [-1, 1]
        String input = "the quick brown fox jumps over the lazy dog";
        int dimensions = 512;
        long seed = 0;

        // when
        double[] vector = normalized(input, dimensions, seed);

        // then
        for (int i = 0; i < dimensions; i++) {
            assertThat("value at " + i + " should be >= -1", vector[i], is(greaterThanOrEqualTo(-1.0)));
            assertThat("value at " + i + " should be <= 1", vector[i], is(lessThanOrEqualTo(1.0)));
        }
    }

    @Test
    public void shouldRankSemanticallySimilarTextsAboveUnrelatedTexts() {
        // given — two paraphrases and one unrelated sentence
        int dimensions = 1536;
        long seed = 42;
        double[] cat1 = normalized("the cat sat on the mat", dimensions, seed);
        double[] cat2 = normalized("a cat sits on a mat", dimensions, seed);
        double[] finance = normalized("quarterly financial report", dimensions, seed);

        // when
        double similarPair = cosine(cat1, cat2);
        double unrelatedPair = cosine(cat1, finance);

        // then — related texts are markedly more similar than unrelated ones
        assertThat("paraphrases should have positive cosine similarity",
            similarPair, is(greaterThan(0.3)));
        assertThat("unrelated texts should be near-orthogonal",
            unrelatedPair, is(lessThan(0.15)));
        assertThat("similar pair must rank above unrelated pair",
            similarPair, is(greaterThan(unrelatedPair + 0.2)));
    }

    @Test
    public void shouldGiveIdenticalTextCosineOfOne() {
        // given
        int dimensions = 768;
        long seed = 7;

        // when
        double[] a = normalized("retrieval augmented generation", dimensions, seed);
        double[] b = normalized("retrieval augmented generation", dimensions, seed);

        // then
        assertThat(cosine(a, b), is(closeTo(1.0, 1e-9)));
    }

    @Test
    public void shouldRankSharedVocabularyAboveDisjointVocabulary() {
        // given — a query and two candidate documents
        int dimensions = 1024;
        long seed = 3;
        double[] query = normalized("how do I configure TLS certificates", dimensions, seed);
        double[] relevant = normalized("configure TLS certificates for the server", dimensions, seed);
        double[] irrelevant = normalized("the weather forecast for tomorrow", dimensions, seed);

        // when
        double relevantScore = cosine(query, relevant);
        double irrelevantScore = cosine(query, irrelevant);

        // then — the retrieval ordering is correct
        assertThat("document sharing vocabulary must rank first",
            relevantScore, is(greaterThan(irrelevantScore)));
    }

    @Test
    public void shouldHandleNonAsciiInputDeterministicallyAndNormalized() {
        // given — accented Latin, CJK, and Cyrillic
        int dimensions = 256;
        long seed = 11;
        String nonAscii = "café 日本語 Привет мир";

        // when
        double[] vector1 = EmbeddingVectors.generateDeterministicVector(nonAscii, dimensions, seed);
        double[] vector2 = EmbeddingVectors.generateDeterministicVector(nonAscii, dimensions, seed);
        EmbeddingVectors.normalizeL2(vector1);

        // then — deterministic, unit length, and non-degenerate
        assertThat(vector1.length, is(dimensions));
        for (int i = 0; i < dimensions; i++) {
            assertThat("element " + i, vector1[i], is(vector2[i] / l2(vector2)));
        }
        double sumOfSquares = 0;
        for (double v : vector1) {
            sumOfSquares += v * v;
        }
        assertThat(Math.sqrt(sumOfSquares), is(closeTo(1.0, 1e-9)));
    }

    @Test
    public void shouldRankNonAsciiOverlapAboveNonAsciiDisjoint() {
        // given
        int dimensions = 512;
        long seed = 5;
        double[] a = normalized("日本語 の テスト", dimensions, seed);
        double[] shared = normalized("日本語 の 例", dimensions, seed);
        double[] disjoint = normalized("Привет мир", dimensions, seed);

        // when / then
        assertThat(cosine(a, shared), is(greaterThan(cosine(a, disjoint))));
    }

    @Test
    public void shouldProduceDeterministicNonZeroVectorForFeaturelessInput() {
        // given — punctuation-only input has no word/char features
        int dimensions = 64;
        long seed = 9;

        // when
        double[] vector1 = EmbeddingVectors.generateDeterministicVector("!!! ??? ...", dimensions, seed);
        double[] vector2 = EmbeddingVectors.generateDeterministicVector("!!! ??? ...", dimensions, seed);

        // then — deterministic and non-degenerate (has a positive norm)
        double norm = l2(vector1);
        assertThat(norm, is(greaterThan(0.0)));
        for (int i = 0; i < dimensions; i++) {
            assertThat(vector1[i], is(vector2[i]));
        }
    }

    @Test
    public void shouldProduceLocaleIndependentVector() {
        // given — an input with an uppercase 'I' whose lowercase form differs
        // under the Turkish locale (I -> dotless ı) when the default-locale
        // toLowerCase is used, which would perturb tokenisation / the vector.
        String input = "I love RAG Interoperability";
        int dimensions = 128;
        long seed = 42;
        Locale originalDefault = Locale.getDefault();
        double[] underOriginalLocale = EmbeddingVectors.generateDeterministicVector(input, dimensions, seed);

        // when — the same generation runs with a Turkish default locale
        double[] underTurkishLocale;
        try {
            Locale.setDefault(Locale.forLanguageTag("tr-TR"));
            underTurkishLocale = EmbeddingVectors.generateDeterministicVector(input, dimensions, seed);
        } finally {
            Locale.setDefault(originalDefault);
        }

        // then — the vector is unaffected by the default locale
        assertThat(underTurkishLocale.length, is(dimensions));
        for (int i = 0; i < dimensions; i++) {
            assertThat("element " + i + " should be locale-independent",
                underTurkishLocale[i], is(underOriginalLocale[i]));
        }
    }

    @Test
    public void shouldReturnEmptyVectorForZeroOrNegativeDimensions() {
        // given / when / then — zero or negative dimensions gracefully yield an
        // empty vector rather than throwing (no floorMod-by-zero).
        assertThat(EmbeddingVectors.generateDeterministicVector("any input", 0, 42).length, is(0));
        assertThat(EmbeddingVectors.generateDeterministicVector("any input", -1, 42).length, is(0));
    }

    private static double l2(double[] v) {
        double s = 0;
        for (double x : v) {
            s += x * x;
        }
        return Math.sqrt(s);
    }
}
