package org.mockserver.client;

import org.mockserver.llm.realtime.GeminiLiveCodec;
import org.mockserver.llm.realtime.OpenAiRealtimeCodec;
import org.mockserver.llm.realtime.RealtimeEvent;
import org.mockserver.llm.realtime.RealtimeModality;
import org.mockserver.llm.realtime.RealtimeProvider;
import org.mockserver.llm.realtime.RealtimeStreamingPhysics;
import org.mockserver.llm.realtime.RealtimeTurn;
import org.mockserver.mock.Expectation;
import org.mockserver.model.HttpWebSocketResponse;
import org.mockserver.model.WebSocketMessage;
import org.mockserver.model.WebSocketMessageMatcher;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.TimeUnit;

import static org.mockserver.model.HttpRequest.request;

/**
 * Fluent builder that stands MockServer up as a mock <b>realtime voice API</b> — either the OpenAI Realtime API
 * or the Google Gemini Live API — over a WebSocket, so an application/agent using those SDKs can be tested
 * offline.
 *
 * <p>It produces a single {@code httpWebSocketResponse} expectation that reuses the generic WebSocket mock
 * primitive: an initial pushed frame (OpenAI {@code session.created}) plus per-incoming-frame
 * {@link WebSocketMessageMatcher matchers} that reply to the client's control messages with the provider-correct
 * scripted event sequence generated by {@link OpenAiRealtimeCodec} / {@link GeminiLiveCodec}. No new action type,
 * DTO, or JSON schema is required — exactly as A2A streaming reuses {@code httpSseResponse}.
 *
 * <p><b>OpenAI Realtime</b> ({@code wss://.../v1/realtime}): the mock pushes {@code session.created} on connect,
 * acknowledges {@code session.update} → {@code session.updated} and {@code conversation.item.create} →
 * {@code conversation.item.created}, and answers each {@code response.create} with the scripted response event
 * sequence (…deltas… → {@code response.done} with usage).
 *
 * <p><b>Gemini Live</b> ({@code BidiGenerateContent}): the mock answers {@code setup} → {@code setupComplete} and
 * each {@code clientContent} turn with the scripted {@code serverContent} chunk stream + {@code turnComplete}.
 *
 * <p>The same script answers every matching frame, so a client that sends {@code response.create} /
 * {@code clientContent} N times receives the scripted turn N times.
 *
 * <pre>
 * RealtimeMockBuilder.openAiRealtime()
 *     .withModel("gpt-realtime")
 *     .respondingWith("The capital of France is Paris.")
 *     .applyTo(mockServerClient);
 * </pre>
 */
public class RealtimeMockBuilder {

    /** Default OpenAI Realtime path. */
    public static final String DEFAULT_OPENAI_REALTIME_PATH = "/v1/realtime";
    /** Default Gemini Live {@code BidiGenerateContent} path. */
    public static final String DEFAULT_GEMINI_LIVE_PATH =
        "/ws/google.ai.generativelanguage.v1beta.GenerativeService.BidiGenerateContent";

    private final RealtimeProvider provider;
    private String path;
    private String model;
    private String subprotocol;
    private String sessionId;
    private RealtimeModality modality = RealtimeModality.AUDIO;
    private int tokensPerSecond = RealtimeStreamingPhysics.DEFAULT_TOKENS_PER_SECOND;
    private long timeToFirstTokenMillis = 0L;
    private RealtimeTurn turn;

    private RealtimeMockBuilder(RealtimeProvider provider, String path) {
        this.provider = provider;
        this.path = path;
    }

    public static RealtimeMockBuilder openAiRealtime() {
        return new RealtimeMockBuilder(RealtimeProvider.OPENAI_REALTIME, DEFAULT_OPENAI_REALTIME_PATH);
    }

    public static RealtimeMockBuilder openAiRealtime(String path) {
        return new RealtimeMockBuilder(RealtimeProvider.OPENAI_REALTIME, path);
    }

    public static RealtimeMockBuilder geminiLive() {
        return new RealtimeMockBuilder(RealtimeProvider.GEMINI_LIVE, DEFAULT_GEMINI_LIVE_PATH);
    }

    public static RealtimeMockBuilder geminiLive(String path) {
        return new RealtimeMockBuilder(RealtimeProvider.GEMINI_LIVE, path);
    }

    public RealtimeMockBuilder withPath(String path) {
        this.path = path;
        return this;
    }

    public RealtimeMockBuilder withModel(String model) {
        this.model = model;
        return this;
    }

    /**
     * The negotiated WebSocket subprotocol. Left unset by default so the handshake accepts whatever the client
     * offers (OpenAI clients carry auth in the subprotocol list, which an offline mock ignores).
     */
    public RealtimeMockBuilder withSubprotocol(String subprotocol) {
        this.subprotocol = subprotocol;
        return this;
    }

    /** OpenAI only — the session id echoed in {@code session.created} / {@code session.updated}. */
    public RealtimeMockBuilder withSessionId(String sessionId) {
        this.sessionId = sessionId;
        return this;
    }

    /** {@link RealtimeModality#AUDIO} (default — transcript + audio deltas) or {@link RealtimeModality#TEXT}. */
    public RealtimeMockBuilder withModality(RealtimeModality modality) {
        if (modality != null) {
            this.modality = modality;
        }
        return this;
    }

    /** Streaming rate for content deltas (default {@value RealtimeStreamingPhysics#DEFAULT_TOKENS_PER_SECOND}). */
    public RealtimeMockBuilder withTokensPerSecond(int tokensPerSecond) {
        this.tokensPerSecond = tokensPerSecond;
        return this;
    }

    /** Extra delay before the first content delta, in milliseconds. */
    public RealtimeMockBuilder withTimeToFirstToken(long millis) {
        this.timeToFirstTokenMillis = millis;
        return this;
    }

    public RealtimeMockBuilder respondingWith(RealtimeTurn turn) {
        this.turn = turn;
        return this;
    }

    public RealtimeMockBuilder respondingWith(String text) {
        this.turn = RealtimeTurn.realtimeTurn(text);
        return this;
    }

    public Expectation[] applyTo(MockServerClient client) {
        return client.upsert(build());
    }

    public Expectation build() {
        RealtimeTurn effectiveTurn = turn != null ? turn : RealtimeTurn.realtimeTurn("");
        RealtimeStreamingPhysics physics = new RealtimeStreamingPhysics(tokensPerSecond, timeToFirstTokenMillis);

        HttpWebSocketResponse wsResponse = HttpWebSocketResponse.webSocketResponse()
            .withCloseConnection(false);
        if (subprotocol != null) {
            wsResponse.withSubprotocol(subprotocol);
        }

        if (provider == RealtimeProvider.OPENAI_REALTIME) {
            // session.created is pushed on connect (server-initiated), before any client message.
            wsResponse.withMessage(WebSocketMessage.webSocketMessage(
                OpenAiRealtimeCodec.sessionCreated(model, sessionId)));
            wsResponse.withMatcher(matcher("(?s).*\"type\"\\s*:\\s*\"session\\.update\".*",
                singleton(OpenAiRealtimeCodec.sessionUpdated(model, sessionId))));
            wsResponse.withMatcher(matcher("(?s).*\"type\"\\s*:\\s*\"conversation\\.item\\.create\".*",
                singleton(OpenAiRealtimeCodec.conversationItemCreated(null))));
            wsResponse.withMatcher(matcher("(?s).*\"type\"\\s*:\\s*\"response\\.create\".*",
                toMessages(OpenAiRealtimeCodec.responseSequence(effectiveTurn, modality, physics))));
        } else {
            wsResponse.withMatcher(matcher("(?s).*\"setup\"\\s*:.*",
                singleton(GeminiLiveCodec.setupComplete())));
            wsResponse.withMatcher(matcher("(?s).*\"clientContent\"\\s*:.*",
                toMessages(GeminiLiveCodec.serverContentSequence(effectiveTurn, modality, physics))));
        }

        return Expectation.when(
            request().withMethod("GET").withPath(path)
        ).thenRespondWithWebSocket(wsResponse);
    }

    private static WebSocketMessageMatcher matcher(String regex, List<WebSocketMessage> responses) {
        return WebSocketMessageMatcher.webSocketMessageMatcher()
            .withTextRegex(regex)
            .withResponses(responses);
    }

    private static List<WebSocketMessage> singleton(String json) {
        List<WebSocketMessage> list = new ArrayList<>();
        list.add(WebSocketMessage.webSocketMessage(json));
        return list;
    }

    /**
     * The bidirectional WebSocket matcher schedules every response frame of a match concurrently, each with its
     * own delay <em>relative to the moment of the match</em> — so equal per-event gaps would race and reorder.
     * To keep the scripted event sequence reliably ordered under normal load (time-ordered dispatch of
     * spaced schedules — not a hard contractual guarantee under extreme scheduler contention) we convert
     * the codec's per-event gaps into
     * monotonically-increasing <em>cumulative absolute</em> delays (each frame at least {@code MIN_STEP_MILLIS}
     * after the previous), which the concurrent scheduler then fires in order.
     */
    private static final long MIN_STEP_MILLIS = 1L;

    private static List<WebSocketMessage> toMessages(List<RealtimeEvent> events) {
        List<WebSocketMessage> list = new ArrayList<>();
        long cumulative = 0L;
        for (RealtimeEvent event : events) {
            cumulative += Math.max(event.delayMillis(), MIN_STEP_MILLIS);
            list.add(WebSocketMessage.webSocketMessage(event.json())
                .withDelay(TimeUnit.MILLISECONDS, cumulative));
        }
        return list;
    }
}
