package org.mockserver.oidc;

import com.fasterxml.jackson.databind.ObjectWriter;
import org.mockserver.authentication.jwt.JWKGenerator;
import org.mockserver.keys.AsymmetricKeyPair;
import org.mockserver.mock.Expectation;
import org.mockserver.model.HttpClassCallback;
import org.mockserver.serialization.ObjectMapperFactory;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import static org.mockserver.model.HttpRequest.request;
import static org.mockserver.model.HttpResponse.response;

/**
 * Generates MockServer {@link Expectation}s that serve a complete set of OIDC/OAuth2
 * identity provider endpoints: discovery, JWKS, token, authorize, userinfo, introspection,
 * revocation, and end-session (logout). Tokens are signed with a key pair (generated by
 * default, or supplied via PEM / JWK) whose public key is exposed via the JWKS endpoint, so
 * OIDC-aware clients can validate tokens end-to-end without any external infrastructure.
 *
 * <p>Tokens are minted at request time by {@link OidcTokenCallback} (so a per-request
 * {@code nonce} from the authorize request can be embedded in the {@code id_token}), not
 * pre-baked at generate time.
 *
 * <p>Usage mirrors the WSDL and OpenAPI importers: call
 * {@link #generate(OidcProviderConfiguration)} with a configuration (or defaults)
 * and upsert the returned expectations into the mock server.
 */
public class OidcProviderGenerator {

    private static final String APPLICATION_JSON = "application/json; charset=utf-8";
    static final String LOGOUT_PATH = "/logout";

    private final ObjectWriter objectWriter = ObjectMapperFactory.createObjectMapper(true, false);

    /**
     * Generates OIDC provider expectations from the given configuration.
     *
     * @param config the provider configuration (must not be null)
     * @return the generated expectations (one per endpoint, never empty)
     */
    public List<Expectation> generate(OidcProviderConfiguration config) {
        if (config == null) {
            throw new IllegalArgumentException("OIDC provider configuration is required");
        }

        // Resolve the signing key pair (generated by default, or supplied via PEM / JWK) for the
        // configured algorithm. The same key both signs tokens (via the minter) and is published at
        // the JWKS endpoint, preserving the sign/publish invariant.
        AsymmetricKeyPair keyPair = OidcKeyProvider.resolveKeyPair(config);
        JWKGenerator jwkGenerator = new JWKGenerator();
        String jwksJson = jwkGenerator.generateJWK(keyPair);

        // Tokens are minted at request time by the OidcTokenCallback (so a per-request nonce can be
        // embedded in the id_token), not pre-baked here.
        OidcTokenMinter tokenMinter = new OidcTokenMinter(config, keyPair);

        List<Expectation> expectations = new ArrayList<>();

        // 1. Discovery document
        expectations.add(buildDiscoveryExpectation(config, keyPair));

        // 2. JWKS endpoint
        expectations.add(buildJwksExpectation(config, jwksJson));

        // 3. Token endpoint (also serves the authorization_code grant exchange)
        expectations.add(buildTokenExpectation(config));

        // 4. Authorize endpoint (authorization-code grant)
        expectations.add(buildAuthorizeExpectation(config));

        // 5. Userinfo endpoint
        expectations.add(buildUserinfoExpectation(config));

        // 6. Introspection endpoint
        expectations.add(buildIntrospectionExpectation(config));

        // 7. Revocation endpoint
        expectations.add(buildRevocationExpectation(config));

        // 8. End-session (logout) endpoint
        expectations.add(buildLogoutExpectation());

        // 9. Device-authorization endpoint (RFC 8628)
        expectations.add(buildDeviceAuthorizationExpectation(config));

        // Register provider state so the /authorize, /token, /introspect and /device_authorization
        // callbacks can complete the flows (issue codes, validate PKCE, mint tokens carrying the nonce,
        // poll device codes, resolve opaque tokens).
        OidcAuthorizationStore.getInstance().registerProvider(
            new OidcAuthorizationStore.Provider(
                config.getAuthorizePath(), config.getTokenPath(), config.getDeviceAuthorizationPath(),
                config, tokenMinter
            )
        );

        return expectations;
    }

    private Expectation buildDiscoveryExpectation(OidcProviderConfiguration config, AsymmetricKeyPair keyPair) {
        String issuer = config.getIssuer();
        String signingAlg = keyPair.getAlgorithm().getJwtAlgorithm();
        Map<String, Object> discovery = new LinkedHashMap<>();
        discovery.put("issuer", issuer);
        discovery.put("authorization_endpoint", issuer + config.getAuthorizePath());
        discovery.put("token_endpoint", issuer + config.getTokenPath());
        discovery.put("userinfo_endpoint", issuer + config.getUserinfoPath());
        discovery.put("jwks_uri", issuer + config.getJwksPath());
        discovery.put("introspection_endpoint", issuer + config.getIntrospectPath());
        discovery.put("revocation_endpoint", issuer + config.getRevokePath());
        discovery.put("end_session_endpoint", issuer + LOGOUT_PATH);
        discovery.put("device_authorization_endpoint", issuer + config.getDeviceAuthorizationPath());
        discovery.put("response_types_supported", Arrays.asList("code", "token", "id_token", "code token", "code id_token"));
        // Advertise the implemented grants, including the RFC 8628 device-code grant.
        discovery.put("grant_types_supported", Arrays.asList(
            "authorization_code", "client_credentials", "refresh_token",
            "urn:ietf:params:oauth:grant-type:device_code"
        ));
        discovery.put("code_challenge_methods_supported", Arrays.asList("S256", "plain"));
        discovery.put("token_endpoint_auth_methods_supported",
            Arrays.asList("client_secret_basic", "client_secret_post", "none"));
        discovery.put("id_token_signing_alg_values_supported", Arrays.asList(signingAlg));
        discovery.put("scopes_supported", config.getScopes());
        discovery.put("subject_types_supported", Arrays.asList("public"));
        discovery.put("claims_supported", Arrays.asList(
            "iss", "sub", "aud", "exp", "iat", "nbf", "nonce", "at_hash",
            "name", "preferred_username", "email", "email_verified", "scope"
        ));

        return new Expectation(
            request()
                .withMethod("GET")
                .withPath("/.well-known/openid-configuration")
        )
            .withId("oidc.discovery")
            .thenRespond(response()
                .withStatusCode(200)
                .withHeader("content-type", APPLICATION_JSON)
                .withBody(serializeToJson(discovery)));
    }

    private Expectation buildJwksExpectation(OidcProviderConfiguration config, String jwksJson) {
        return new Expectation(
            request()
                .withMethod("GET")
                .withPath(config.getJwksPath())
        )
            .withId("oidc.jwks")
            .thenRespond(response()
                .withStatusCode(200)
                .withHeader("content-type", APPLICATION_JSON)
                .withBody(jwksJson));
    }

    private Expectation buildTokenExpectation(OidcProviderConfiguration config) {
        // A class callback so the same /token endpoint serves both the existing grants
        // (client_credentials, refresh_token — minting tokens at request time) and the
        // authorization_code grant (validating the code + PKCE, then minting tokens carrying nonce).
        return new Expectation(
            request()
                .withMethod("POST")
                .withPath(config.getTokenPath())
        )
            .withId("oidc.token")
            .thenRespond(HttpClassCallback.callback(OidcTokenCallback.class.getName()));
    }

    private Expectation buildAuthorizeExpectation(OidcProviderConfiguration config) {
        // A class callback so /authorize can echo the dynamic `state`, mint an authorization
        // `code`, record any PKCE challenge, and 302-redirect back to the redirect_uri.
        return new Expectation(
            request()
                .withMethod("GET")
                .withPath(config.getAuthorizePath())
        )
            .withId("oidc.authorize")
            .thenRespond(HttpClassCallback.callback(OidcAuthorizationCodeCallback.class.getName()));
    }

    private Expectation buildUserinfoExpectation(OidcProviderConfiguration config) {
        Map<String, Object> userinfo = new LinkedHashMap<>();
        userinfo.put("sub", config.getSubject());
        if (config.getAdditionalClaims() != null) {
            userinfo.putAll(config.getAdditionalClaims());
        }

        return new Expectation(
            request()
                .withMethod("GET")
                .withPath(config.getUserinfoPath())
        )
            .withId("oidc.userinfo")
            .thenRespond(response()
                .withStatusCode(200)
                .withHeader("content-type", APPLICATION_JSON)
                .withBody(serializeToJson(userinfo)));
    }

    private Expectation buildIntrospectionExpectation(OidcProviderConfiguration config) {
        // A class callback so introspection can resolve opaque access tokens (RFC 7662): when the
        // presented `token` is a stored opaque token it echoes the stored claims (active:true), an
        // unknown/expired opaque token yields active:false, and otherwise it falls back to the
        // provider's static introspection result (active driven by issueExpiredToken).
        return new Expectation(
            request()
                .withMethod("POST")
                .withPath(config.getIntrospectPath())
        )
            .withId("oidc.introspect")
            .thenRespond(HttpClassCallback.callback(OidcIntrospectionCallback.class.getName()));
    }

    private Expectation buildDeviceAuthorizationExpectation(OidcProviderConfiguration config) {
        // A class callback so /device_authorization can mint a device_code + user_code per request
        // (RFC 8628 §3.2) and record them in the store for the token-endpoint polling exchange.
        return new Expectation(
            request()
                .withMethod("POST")
                .withPath(config.getDeviceAuthorizationPath())
        )
            .withId("oidc.deviceAuthorization")
            .thenRespond(HttpClassCallback.callback(OidcDeviceAuthorizationCallback.class.getName()));
    }

    private Expectation buildRevocationExpectation(OidcProviderConfiguration config) {
        return new Expectation(
            request()
                .withMethod("POST")
                .withPath(config.getRevokePath())
        )
            .withId("oidc.revoke")
            .thenRespond(response()
                .withStatusCode(200)
                .withHeader("content-type", APPLICATION_JSON)
                .withBody(""));
    }

    private Expectation buildLogoutExpectation() {
        // A class callback so /logout can honour an optional post_logout_redirect_uri (302) and
        // otherwise return a simple 200, mirroring an OIDC RP-initiated logout (end_session_endpoint).
        return new Expectation(
            request()
                .withMethod("GET")
                .withPath(LOGOUT_PATH)
        )
            .withId("oidc.logout")
            .thenRespond(HttpClassCallback.callback(OidcLogoutCallback.class.getName()));
    }

    private String serializeToJson(Object value) {
        try {
            return objectWriter.writeValueAsString(value);
        } catch (Exception e) {
            throw new RuntimeException("Failed to serialize OIDC response to JSON", e);
        }
    }
}
