#!/usr/bin/env python3
"""Provision the "MockServer - UI Feature Usefulness" dashboard in PostHog.

The cookieless dashboard-usage analytics baked into released MockServer images
sends events to PostHog Cloud EU using a *write-only ingest key* (``phc_...``).
That key cannot create dashboards or insights - that needs a **personal API
key** (``phx_...``) scoped to ``insight:write`` + ``dashboard:write`` for the
project (PostHog -> Settings -> Personal API keys).

This script (re)creates a curated dashboard answering "which dashboard UI
features and tabs do users actually use". Committing it keeps the dashboard
definition in version control so it can be rebuilt or evolved deliberately
rather than hand-clicked.

Usage::

    export POSTHOG_PERSONAL_API_KEY=phx_...       # required (never commit this)
    export POSTHOG_HOST=https://eu.posthog.com    # optional (default EU app host)
    export POSTHOG_PROJECT_ID=209901              # optional (auto-resolved if unset)
    python3 scripts/analytics/create_posthog_dashboard.py
    python3 scripts/analytics/create_posthog_dashboard.py --dry-run   # print payloads only

Re-running creates a *new* dashboard each time (PostHog has no natural unique
key for dashboards); delete the old one in the UI if you are iterating.

Data model (see mockserver-ui/src/lib/analytics.ts). The analytics is
**cookieless** (``persistence:'memory'``): ``distinct_id`` is a fresh random id
per page-load, so ``count(DISTINCT distinct_id)`` means "unique SESSIONS", never
people, and no cross-session retention is possible. Events and their properties:

    app_open     {app_version, surface, distribution, theme}
    view_change  {view}          # one of the 21 dashboard tabs (store ALL_VIEWS)
    feature_used {feature, mode}  # feature in a closed 7-value set; mode quick|advanced
    error_shown  {category}       # coarse error bucket, never a free-text message
"""
import json
import os
import sys
import urllib.error
import urllib.request

DASHBOARD_NAME = "MockServer - UI Feature Usefulness"
DASHBOARD_DESC = (
    "Which dashboard UI features and tabs users actually use. Cookieless: "
    "distinct_id = one browser session (not a person), so counts are sessions, "
    "not people, and there is no cross-session retention. Default window: last "
    "30 days - edit the INTERVAL in each insight's SQL to change it. "
    "Generated by scripts/analytics/create_posthog_dashboard.py."
)

# The rolling window every insight uses. A single constant so it is trivial to
# retune (e.g. "now() - INTERVAL 90 DAY") in one place.
WINDOW = "now() - INTERVAL 30 DAY"

# Each tile is an (name, description, hogql) triple, rendered as a SQL insight
# (DataVisualizationNode). They default to a results table in the UI; use the
# chart-type selector to switch the ranking/trend tiles to bar/line.
INSIGHTS = [
    (
        "1 Feature usefulness - ranked (uses, reach, adoption %)",
        "The headline. Per feature: total uses, how many distinct sessions used "
        "it, what % of all sessions touched it (adoption), and depth (uses per "
        "using-session). Sort by adoption for the most broadly-useful features.",
        f"""SELECT
    properties.feature AS feature,
    count() AS uses,
    count(DISTINCT distinct_id) AS sessions_using,
    round(100.0 * count(DISTINCT distinct_id) / (
        SELECT count(DISTINCT distinct_id) FROM events
        WHERE event = 'app_open' AND timestamp > {WINDOW}
    ), 1) AS pct_of_sessions,
    round(count() / count(DISTINCT distinct_id), 2) AS uses_per_using_session
FROM events
WHERE event = 'feature_used' AND timestamp > {WINDOW}
GROUP BY feature
ORDER BY sessions_using DESC""",
    ),
    (
        "2 Most-used features (volume)",
        "Raw count of feature_used per feature. Good as a bar chart.",
        f"""SELECT properties.feature AS feature, count() AS uses
FROM events WHERE event = 'feature_used' AND timestamp > {WINDOW}
GROUP BY feature ORDER BY uses DESC""",
    ),
    (
        "3 Feature reach (distinct sessions)",
        "How many distinct sessions used each feature - breadth, not volume. A "
        "feature with high reach but low volume is broadly but lightly useful.",
        f"""SELECT properties.feature AS feature, count(DISTINCT distinct_id) AS sessions
FROM events WHERE event = 'feature_used' AND timestamp > {WINDOW}
GROUP BY feature ORDER BY sessions DESC""",
    ),
    (
        "4 Most-visited tabs (view_change)",
        "Which dashboard tabs users open. Visits and distinct sessions per view.",
        f"""SELECT properties.view AS view, count() AS visits, count(DISTINCT distinct_id) AS sessions
FROM events WHERE event = 'view_change' AND timestamp > {WINDOW}
GROUP BY view ORDER BY sessions DESC""",
    ),
    (
        "5 Feature usage trend (daily)",
        "feature_used per day per feature. Switch to a line chart and break down "
        "by feature to see which features are growing or fading.",
        f"""SELECT toStartOfDay(timestamp) AS day, properties.feature AS feature, count() AS uses
FROM events WHERE event = 'feature_used' AND timestamp > {WINDOW}
GROUP BY day, feature ORDER BY day ASC""",
    ),
    (
        "6 Quick vs Advanced mode",
        "Where the UI reports a mode, are users on the quick or advanced path?",
        f"""SELECT properties.mode AS mode, count() AS uses
FROM events WHERE event = 'feature_used' AND properties.mode IS NOT NULL AND timestamp > {WINDOW}
GROUP BY mode ORDER BY uses DESC""",
    ),
    (
        "7 Friction - errors by category",
        "error_shown by coarse category. A feature that is 'used' but errors a "
        "lot is not actually useful - cross-reference with tiles 1 and 5.",
        f"""SELECT properties.category AS category, count() AS errors, count(DISTINCT distinct_id) AS sessions
FROM events WHERE event = 'error_shown' AND timestamp > {WINDOW}
GROUP BY category ORDER BY errors DESC""",
    ),
    (
        "8 Engagement - features per session",
        "Sessions (app_open), total feature uses, and features-per-session - how "
        "deeply an average session engages beyond just opening the dashboard.",
        f"""SELECT
    uniqIf(distinct_id, event = 'app_open') AS sessions,
    countIf(event = 'feature_used') AS feature_uses,
    round(countIf(event = 'feature_used') / nullIf(uniqIf(distinct_id, event = 'app_open'), 0), 2) AS features_per_session
FROM events WHERE timestamp > {WINDOW}""",
    ),
    (
        "9 Context - distribution & version mix",
        "Which artefact (docker-standard/graaljs/clustered, helm, binary, jar) "
        "and app version the sessions came from - context for the feature numbers.",
        f"""SELECT properties.distribution AS distribution, properties.app_version AS version,
    count(DISTINCT distinct_id) AS sessions
FROM events WHERE event = 'app_open' AND timestamp > {WINDOW}
GROUP BY distribution, version ORDER BY sessions DESC""",
    ),
]


def api(host, key, method, path, body=None):
    """Call the PostHog API, exiting with a readable message on any failure."""
    url = f"{host.rstrip('/')}{path}"
    data = json.dumps(body).encode() if body is not None else None
    req = urllib.request.Request(url, data=data, method=method)
    req.add_header("Authorization", f"Bearer {key}")
    req.add_header("Content-Type", "application/json")
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            return json.loads(resp.read().decode())
    except urllib.error.HTTPError as exc:
        sys.exit(f"API {method} {path} failed: HTTP {exc.code}\n{exc.read().decode()[:600]}")
    except urllib.error.URLError as exc:
        sys.exit(
            f"API {method} {path} unreachable: {exc}\n"
            "(behind a TLS-inspection proxy? point SSL_CERT_FILE at your CA bundle.)"
        )


def insight_query(hogql):
    return {"kind": "DataVisualizationNode", "source": {"kind": "HogQLQuery", "query": hogql}}


def resolve_project(host, key):
    """Return the project id from the env var, else the personal key's default team."""
    if os.environ.get("POSTHOG_PROJECT_ID"):
        return os.environ["POSTHOG_PROJECT_ID"]
    try:
        proj = api(host, key, "GET", "/api/projects/@current/")
        if proj.get("id"):
            return proj["id"]
    except SystemExit:
        pass
    me = api(host, key, "GET", "/api/users/@me/")
    team = me.get("team") or {}
    if team.get("id"):
        return team["id"]
    sys.exit("Could not auto-resolve the project id; set POSTHOG_PROJECT_ID.")


def main():
    dry = "--dry-run" in sys.argv
    host = os.environ.get("POSTHOG_HOST", "https://eu.posthog.com")
    key = os.environ.get("POSTHOG_PERSONAL_API_KEY", "")

    if dry:
        print(f"# DRY RUN - host={host}, project={os.environ.get('POSTHOG_PROJECT_ID') or '<auto>'}\n")
        print(f"POST /api/projects/<id>/dashboards/  name={DASHBOARD_NAME!r}\n")
        for name, _desc, hogql in INSIGHTS:
            print(f"POST /api/projects/<id>/insights/  name={name!r}")
            print(json.dumps(insight_query(hogql), indent=2))
            print()
        print(f"# {len(INSIGHTS)} insights would be created and attached to the dashboard.")
        return

    if not key:
        sys.exit("Set POSTHOG_PERSONAL_API_KEY (a phx_... personal API key). Or pass --dry-run.")

    project = resolve_project(host, key)
    print(f"Project: {project}")

    dashboard = api(host, key, "POST", f"/api/projects/{project}/dashboards/",
                    {"name": DASHBOARD_NAME, "description": DASHBOARD_DESC})
    dashboard_id = dashboard.get("id")
    if not dashboard_id:
        sys.exit(f"Unexpected dashboard response (no 'id'): {str(dashboard)[:200]}")
    print(f"Created dashboard #{dashboard_id}: {DASHBOARD_NAME}")

    for name, desc, hogql in INSIGHTS:
        api(host, key, "POST", f"/api/projects/{project}/insights/", {
            "name": name,
            "description": desc,
            "query": insight_query(hogql),
            "dashboards": [dashboard_id],
        })
        print(f"  + {name}")

    print(f"\nDone. Open: {host.rstrip('/')}/project/{project}/dashboard/{dashboard_id}")


if __name__ == "__main__":
    main()
